os: linux
dist: bionic

services:
  - docker

language: python
python:
  - '3.7'
  - '3.8'

cache:
  pip: true

install:
  - pip install -r requirements.txt

script:
  - echo "Nothing here..."

deploy:
  provider: heroku
  strategy: api
  edge: true
  on: master
