os: linux
dist: bionic

services:
  - docker

language: python
python:
  - '3.7'
  - '3.8'

install:
  - pip install flake8
  - docker build . -t ipgit

before_script:
  - docker run --rm -itd -p 8000:8000 ipgit
  - sleep 5
  - docker ps -a

script:
  - flake8 --statistics ipgit/
  - git clone https://github.com/ipfs/go-ipfs.git
  - cd go-ipfs
  - git remote add local http://localhost:8000/go-ipfs
  - git push local master
