os: linux
dist: bionic

services:
  - docker

language: python
python:
  - '3.7'
  - '3.8'

cache:
  pip: true

install:
  - pip install -r requirements.txt
  - make install

before_script:
  - ipfs daemon --offline --init
  - sleep 5
  - 2> /dev/null 1> /dev/null uvicorn app:app & disown
  - sleep 5
  - make local

script:
  - git push local master
