os: linux
dist: bionic

language: python
python:
  - '3.7'
  - '3.8'

cache:
  pip: true

install:
  - pip install -r requirements.txt
  - sudo make install

before_script:
  - ipfs daemon --offline --init > /dev/null & disown
  - sleep 5
  - uvicorn ipgit:app --log-level error > /dev/null & disown
  - sleep 5
  - make local

script:
  - git push local master
