os: linux
dist: bionic

services:
  - docker

language: python
python:
  - '3.7'
  - '3.8'

cache:
  pip: true

install:
  - pip install -r requirements.txt

before_script:
  - docker run -itd -p 5001:5001 ipfs/go-ipfs:v0.6.0 daemon --offline --init
  - sleep 5
  - uvicorn app:app & disown
  - sleep 5
  - make local

script:
  - git push ipfs HEAD
