os: linux
dist: bionic

services:
  - docker

language: python
python:
  - '3.7'
  - '3.8'

cache:
  pip: true

install:
  - pip install -r requirements.txt

before_script:
  - docker run -itd -p 5001:5001 ipfs/go-ipfs daemon --offline --init
  - uvicorn app:app & disown
  - sleep 10
  - make local

script:
  - git push ipfs HEAD
