os: linux
dist: bionic

services:
  - docker

language: python
python:
  - '3.7'
  - '3.8'

install:
  - pip install -r requirements.txt

before_script:
  - docker run --rm -itd -p 5001:5001 ipfs/go-ipfs daemon --offline

script:
  - python t.py
