os: linux
dist: bionic

language: python
python:
  - '3.6'
  - '3.7'
  - '3.8'

cache:
  pip: true

install:
  - pip install -r requirements.txt
  - sudo make install

before_script:
  - 2>/dev/null 1>&2 ipfs daemon --offline --init & disown
  - sleep 5
  - 2>/dev/null 1>&2 uvicorn ipgit:app & disown
  - sleep 5

script:
  - git init test
  - cd test
  - echo "test" > test.txt
  - git add test.txt
  - git commit -m "test file"
  - git remote add local http://localhost:8000/test
  - git push local master
