name: build

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'
          cache: 'pip'
      - run: pip install -r requirements.txt

  flake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - run: pip install flake8
      - run: flake8 --statistics ipgit/

  image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker build . -t ipgit
      - name: Run container
        run: |
          docker run --rm -itd -p 8000:8000 ipgit
          sleep 10
          docker ps -a
      - name: Test container
        run: |
          git clone https://github.com/ipfs/go-ipfs.git
          cd go-ipfs
          git remote add local http://localhost:8000/go-ipfs
          git push local master
